version: "3.5"

services:
  odoo:
    image: odoo
    container_name: odoo
    build: ./
    ports:
    - "8069:8069"
    environment:
    - HOST=db
    - USER=odoo
    - PASSWORD=odoo
    volumes:
    - filestore:/var/lib/odoo
    - ./addons:/mnt/extra_addons
    - ./odoo.conf:/etc/odoo/odoo.conf
    # entrypoint: "/usr/bin/odoo -c /etc/odoo/odoo.conf --dev all"
    command: odoo -u estate -d test
  db:
    image: postgres:13
    container_name: db
    environment:
    - POSTGRES_DB=postgres
    - POSTGRES_USER=odoo
    - POSTGRES_PASSWORD=odoo
    - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
    - pgdata:/var/lib/postgresql/data/pgdata

volumes:
  filestore:
  pgdata: